/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pertemuan15;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class RawatInap extends javax.swing.JFrame {
    DecimalFormat df = (DecimalFormat)DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols dfs = new DecimalFormatSymbols();
    double totalObat = 0;
    /**
     * Creates new form RawatInap
     */
    public RawatInap() {
        initComponents();
        buttonGroup1.add(rbTunai);
        buttonGroup1.add(rbKK);
        btnHitung.setEnabled(false);
        btnTambahObat.setEnabled(false);
        cbxDokter.setEnabled(false);
        cbxNamaObat.setEnabled(false);
        spinJml.setEnabled(false);
        rbTunai.setEnabled(false);
        rbKK.setEnabled(false);
        
        rbTunai.setSelected(true);
        this.setLocationRelativeTo(null);
    }
    
    public class Pembayaran {
    public double grandTotal(double jasa, double totalObat, double metode) {
        return jasa + totalObat + metode;
    }

        private double hitBiayaObat(int jml, double harga) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }


    private void totalBiayaPengobatan() {
        dfs.setCurrencySymbol("Rp. ");
        dfs.setMonetaryDecimalSeparator(',');
        dfs.setGroupingSeparator('.');
        df.setDecimalFormatSymbols(dfs);
        double jasa = Double.parseDouble(lblTarif.getText());
        
        double totalObat = Double.parseDouble(lblTotalObat.getText());
        Pembayaran a = new Pembayaran();
        double metode;
        
        if (rbTunai.isSelected()) {
            metode = 0;
        } else {
            metode = (jasa + totalObat) * 0.02;
        }
        double jumlah = a.grandTotal(jasa, totalObat, metode);
        
        lblGrandTotal.setText(df.format(jumlah));
    }
    
    private void totalBiayaObat() {
        DefaultTableModel dataModel = (DefaultTableModel) tblObat.getModel();
        int jumlah = dataModel.getRowCount();
        
        for (int i = 0; i < jumlah; i++) {
            double subTotal = Double.parseDouble(dataModel.getValueAt(i,3).toString());
            totalObat += subTotal;
        }
        dfs.setCurrencySymbol("Rp. ");
        dfs.setMonetaryDecimalSeparator(',');
        dfs.setGroupingSeparator('.');
        df.setDecimalFormatSymbols(dfs);
        
        lblTotalObat.setText(String.valueOf(totalObat));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRekamMedik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxDokter = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblTarif = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxNamaObat = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        spinJml = new javax.swing.JSpinner();
        btnTambahObat = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblObat = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        rbKK = new javax.swing.JRadioButton();
        rbTunai = new javax.swing.JRadioButton();
        lblGrandTotal = new javax.swing.JLabel();
        lblTotalObat = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Form Pembayaran Pasien Rawat Jalan");

        jLabel2.setText("Medic Record :");

        txtRekamMedik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRekamMedikActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Pasien :");

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Dokter :");

        cbxDokter.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        cbxDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Rama Dani Putra ", "Dr. Jonathan Ham", "Dr. Dina Febriani Sp.D.V.E", "Dr. Yahaziel Yason Wijaya " }));
        cbxDokter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDokterItemStateChanged(evt);
            }
        });
        cbxDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDokterActionPerformed(evt);
            }
        });

        jLabel5.setText("Tarif  :");

        lblTarif.setText("0");

        jLabel7.setText("Nama Obat :");

        cbxNamaObat.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        cbxNamaObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACE Inhibitor", "Acetylcysteine Inhalasi", "Actemra", "Breathy Tetes Hidung", "Paracetamol (Acetaminophen)" }));
        cbxNamaObat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNamaObatItemStateChanged(evt);
            }
        });
        cbxNamaObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNamaObatActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga :");

        lblHarga.setText("0");

        jLabel10.setText("Jumlah :");

        jLabel11.setText("Sub Total :");

        lblSubTotal.setText("0");

        spinJml.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinJmlStateChanged(evt);
            }
        });
        spinJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spinJmlKeyTyped(evt);
            }
        });

        btnTambahObat.setText("Tambah Obat");
        btnTambahObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahObatMouseClicked(evt);
            }
        });
        btnTambahObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahObatActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Obat", "Harga", "Jumlah", "Sub Total"
            }
        ));
        jScrollPane2.setViewportView(tblObat);

        jLabel13.setText("Metode Pembayaran :");

        rbKK.setText("Kredit");
        rbKK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbKKMouseClicked(evt);
            }
        });
        rbKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKKActionPerformed(evt);
            }
        });

        rbTunai.setText("Tunai");
        rbTunai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbTunaiMouseClicked(evt);
            }
        });
        rbTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTunaiActionPerformed(evt);
            }
        });

        lblGrandTotal.setText("Total Biaya yang dibayar :");

        lblTotalObat.setText("Total Biaya Obat :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTambahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxDokter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxNamaObat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtRekamMedik, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rbTunai)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbKK))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGrandTotal)
                                    .addComponent(lblTotalObat))))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRekamMedik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTarif))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(lblHarga)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(lblSubTotal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(spinJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbTunai)
                            .addComponent(rbKK))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(lblTotalObat)
                        .addGap(18, 18, 18)
                        .addComponent(lblGrandTotal)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRekamMedikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRekamMedikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRekamMedikActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cbxDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDokterActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int jml = (Integer)spinJml.getValue();
        double harga = Double.parseDouble(lblHarga.getText());
        
        Pembayaran byr = new Pembayaran();
        double jumlah = byr.hitBiayaObat(jml, harga);
        
        lblSubTotal.setText(String.valueOf(jumlah));
        btnTambahObat.setEnabled(true);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbxNamaObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNamaObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNamaObatActionPerformed

    private void rbTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTunaiActionPerformed

    private void rbKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKKActionPerformed

    private void cbxNamaObatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNamaObatItemStateChanged
        // TODO add your handling code here:
        switch (cbxNamaObat.getSelectedIndex()) {
            case 0:
                lblHarga.setText("2500");
                break;
            case 1:
                lblHarga.setText("3000");
                break;
            case 2:
                lblHarga.setText("2000");
                break;
            case 3:
                lblHarga.setText("1000");
                break;
            case 4:
                lblHarga.setText("2000");
                break;
        }
        spinJml.setEnabled(true);
    }//GEN-LAST:event_cbxNamaObatItemStateChanged

    private void btnTambahObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahObatActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel)tblObat.getModel();
        ArrayList list = new ArrayList<>();
        
        tblObat.setAutoCreateColumnsFromModel(true);
        list.add(cbxNamaObat.getSelectedItem());
        list.add(lblHarga.getText());
        list.add(spinJml.getValue());
        list.add(lblSubTotal.getText());
        
        dataModel.addRow(list.toArray());
        totalBiayaObat();
        totalBiayaPengobatan();
        rbTunai.setEnabled(true);
        rbKK.setEnabled(true);
    }//GEN-LAST:event_btnTambahObatActionPerformed

    private void rbKKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbKKMouseClicked
        // TODO add your handling code here:
        totalBiayaPengobatan();
    }//GEN-LAST:event_rbKKMouseClicked

    private void btnTambahObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahObatMouseClicked
        // TODO add your handling code here:
        btnTambahObat.setEnabled(false);
    }//GEN-LAST:event_btnTambahObatMouseClicked

    private void spinJmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spinJmlKeyTyped
        // TODO add your handling code here:
        btnHitung.setEnabled(true);
    }//GEN-LAST:event_spinJmlKeyTyped

    private void rbTunaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbTunaiMouseClicked
        // TODO add your handling code here:
        totalBiayaPengobatan();
    }//GEN-LAST:event_rbTunaiMouseClicked

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        cbxDokter.setEnabled(true);
    }//GEN-LAST:event_jTextField2FocusLost

    private void cbxDokterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDokterItemStateChanged
        // TODO add your handling code here:
        switch (cbxDokter.getSelectedIndex()) {
            case 0:
                lblTarif.setText("355000");
                break;
            case 1:
                lblTarif.setText("300000");
                break;
            case 2:
                lblTarif.setText("400000");
                break;
            case 3:
                lblTarif.setText("500000");
                break;
        }
        cbxNamaObat.setEnabled(true);
    }//GEN-LAST:event_cbxDokterItemStateChanged

    private void spinJmlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinJmlStateChanged
        // TODO add your handling code here:
        btnHitung.setEnabled(true);
    }//GEN-LAST:event_spinJmlStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RawatInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RawatInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RawatInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RawatInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RawatInap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnTambahObat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxDokter;
    private javax.swing.JComboBox<String> cbxNamaObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTarif;
    private javax.swing.JLabel lblTotalObat;
    private javax.swing.JRadioButton rbKK;
    private javax.swing.JRadioButton rbTunai;
    private javax.swing.JSpinner spinJml;
    private javax.swing.JTable tblObat;
    private javax.swing.JTextField txtRekamMedik;
    // End of variables declaration//GEN-END:variables
}
